Repository mesosphere/universe, pull requests merged in 2018-11, with the labels that each got.

#2039 Bump converter resources
  converter/marathon.json
Labels: ready-for-review

#2040 Release hdfs 2.4.0-2.6.0-cdh5.11.0 (automated commit)
  repo/packages/H/hdfs/400/config.json
  repo/packages/H/hdfs/400/marathon.json.mustache
  repo/packages/H/hdfs/400/package.json
  repo/packages/H/hdfs/400/resource.json
Labels: do-not-merge, ready-for-review

#2035 Release cassandra 2.4.0-3.0.16 (automated commit)
  repo/packages/C/cassandra/400/config.json
  repo/packages/C/cassandra/400/marathon.json.mustache
  repo/packages/C/cassandra/400/package.json
  repo/packages/C/cassandra/400/resource.json
Labels: ready-for-review

#2033 Release confluent-kafka 2.4.0-4.1.1 (automated commit)
  repo/packages/C/confluent-kafka/400/config.json
  repo/packages/C/confluent-kafka/400/marathon.json.mustache
  repo/packages/C/confluent-kafka/400/package.json
  repo/packages/C/confluent-kafka/400/resource.json
Labels: ready-for-review

#2030 Release datastax-dse 2.4.0-5.1.10 (automated commit)
  repo/packages/D/datastax-dse/400/config.json
  repo/packages/D/datastax-dse/400/marathon.json.mustache
  repo/packages/D/datastax-dse/400/package.json
  repo/packages/D/datastax-dse/400/resource.json
Labels: ready-for-review

#2029 Release datastax-ops 2.4.0-6.1.9 (automated commit)
  repo/packages/D/datastax-ops/400/config.json
  repo/packages/D/datastax-ops/400/marathon.json.mustache
  repo/packages/D/datastax-ops/400/package.json
  repo/packages/D/datastax-ops/400/resource.json
Labels: ready-for-review

#2018 NexCloud changes name to nexclipper-agent
  repo/packages/N/nexclipper-agent/0/config.json
  repo/packages/N/nexclipper-agent/0/marathon.json.mustache
  repo/packages/N/nexclipper-agent/0/package.json
  repo/packages/N/nexclipper-agent/0/resource.json
  repo/packages/N/nexcloud/0/package.json
Labels: awaiting-testing-approval

#2041 adding zk-connection-timeout to the 1.4.x packages
  repo/packages/M/marathon/33/config.json
  repo/packages/M/marathon/33/marathon.json.mustache
  repo/packages/M/marathon/33/package.json
  repo/packages/M/marathon/33/resource.json
Labels: ready-for-review

#2043 Release portworx-confluent-kafka 1.3-2.3.0-4.1.1 (automated commit)
  repo/packages/P/portworx-confluent-kafka/0/config.json
  repo/packages/P/portworx-confluent-kafka/0/marathon.json.mustache
  repo/packages/P/portworx-confluent-kafka/0/package.json
  repo/packages/P/portworx-confluent-kafka/0/resource.json
Labels: awaiting-testing-approval

#2045 Catch DC/OS 1.13 user agents in Docker Nginx config
  docker/local-universe/default.conf
  docker/server/nginx/etc/nginx/conf.d/universe.marathon.mesos.conf
Labels: ready-for-review

#2048 Release hello-world 3.0.0-0.54.3 (automated commit)
  repo/packages/H/hello-world/300/config.json
  repo/packages/H/hello-world/300/marathon.json.mustache
  repo/packages/H/hello-world/300/package.json
  repo/packages/H/hello-world/300/resource.json
Labels: ready-for-review

#2060 Release kubernetes 2.1.0-1.12.3 (automated commit)
  repo/packages/K/kubernetes/1200/config.json
  repo/packages/K/kubernetes/1200/marathon.json.mustache
  repo/packages/K/kubernetes/1200/package.json
  repo/packages/K/kubernetes/1200/resource.json
Labels: ready-for-review

#2059 Release kubernetes-cluster 2.1.0-1.12.3 (automated commit)
  repo/packages/K/kubernetes-cluster/200/config.json
  repo/packages/K/kubernetes-cluster/200/marathon.json.mustache
  repo/packages/K/kubernetes-cluster/200/package.json
  repo/packages/K/kubernetes-cluster/200/resource.json
Labels: ready-for-review

#2066 Update user agent for local universe
  docker/server/nginx/etc/nginx/conf.d/universe.marathon.mesos.conf
Labels: ready-for-review

#2067 Release dcos-core-cli 1.12-patch.2
  repo/packages/D/dcos-core-cli/1202/package.json
  repo/packages/D/dcos-core-cli/1202/resource.json
Labels: ready-for-review
