Repository mesosphere/universe, pull requests merged in 2018-09, with the labels that each got.

#1969 Release kubernetes 1.2.2-1.10.7 (automated commit)
  repo/packages/K/kubernetes/800/config.json
  repo/packages/K/kubernetes/800/marathon.json.mustache
  repo/packages/K/kubernetes/800/package.json
  repo/packages/K/kubernetes/800/resource.json
Labels: ready-for-review, ready-to-merge

#1983 Release beta-mke 2.0.0-1.12.0-beta (automated commit)
  repo/packages/B/beta-mke/0/config.json
  repo/packages/B/beta-mke/0/marathon.json.mustache
  repo/packages/B/beta-mke/0/package.json
  repo/packages/B/beta-mke/0/resource.json
Labels: ready-to-merge

#1984 Release beta-kubernetes 2.0.0-1.12.0-beta (automated commit)
  repo/packages/B/beta-kubernetes/0/config.json
  repo/packages/B/beta-kubernetes/0/marathon.json.mustache
  repo/packages/B/beta-kubernetes/0/package.json
  repo/packages/B/beta-kubernetes/0/resource.json
Labels: ready-to-merge

#1833 Support DC/OS 1.13 and Improve user facing error messages of universe converter
  converter/Dockerfile
  converter/README.md
  converter/marathon.json
  converter/service/converter.py
  scripts/gen_universe.py
Labels: wip

#1975 Release kafka-zookeeper 2.4.0-3.4.13 (automated commit)
  repo/packages/K/kafka-zookeeper/300/config.json
  repo/packages/K/kafka-zookeeper/300/marathon.json.mustache
  repo/packages/K/kafka-zookeeper/300/package.json
  repo/packages/K/kafka-zookeeper/300/resource.json
Labels: do-not-merge, ready-for-review

#1977 Release confluent-zookeeper 2.4.0-4.0.0e (automated commit)
  repo/packages/C/confluent-zookeeper/300/config.json
  repo/packages/C/confluent-zookeeper/300/marathon.json.mustache
  repo/packages/C/confluent-zookeeper/300/package.json
  repo/packages/C/confluent-zookeeper/300/resource.json
Labels: do-not-merge, ready-for-review
