Repository mesosphere/universe, pull requests merged in 2019-10, with the labels that each got.

#2400 Update build definition schema for package registry CLI
  repo/meta/schema/build-definition-schema.json
Labels: ready-for-review

#2398 Do not populate lastUpdated field in package.json : Revert #2391 partially
  scripts/gen_universe.py
Labels: ready-for-review

#2403 Release kubernetes 2.4.3-1.15.3 (automated commit)
  repo/packages/K/kubernetes/2400/config.json
  repo/packages/K/kubernetes/2400/marathon.json.mustache
  repo/packages/K/kubernetes/2400/package.json
  repo/packages/K/kubernetes/2400/resource.json
Labels: ready-for-review

#2402 Release kubernetes-cluster 2.4.3-1.15.3 (automated commit)
  repo/packages/K/kubernetes-cluster/1400/config.json
  repo/packages/K/kubernetes-cluster/1400/marathon.json.mustache
  repo/packages/K/kubernetes-cluster/1400/package.json
  repo/packages/K/kubernetes-cluster/1400/resource.json
Labels: ready-for-review

#2406 Release hello-world 3.2.0-0.57.1 (automated commit)
  repo/packages/H/hello-world/600/config.json
  repo/packages/H/hello-world/600/marathon.json.mustache
  repo/packages/H/hello-world/600/package.json
  repo/packages/H/hello-world/600/resource.json
Labels: ready-for-review

#2399 Release hdfs 2.7.0-3.2.1 (automated commit)
  repo/packages/H/hdfs/700/config.json
  repo/packages/H/hdfs/700/marathon.json.mustache
  repo/packages/H/hdfs/700/package.json
  repo/packages/H/hdfs/700/resource.json
Labels: ready-for-review

#2404 Release confluent-kafka 2.8.0-5.3.1 (automated commit)
  repo/packages/C/confluent-kafka/800/config.json
  repo/packages/C/confluent-kafka/800/marathon.json.mustache
  repo/packages/C/confluent-kafka/800/package.json
  repo/packages/C/confluent-kafka/800/resource.json
Labels: ready-for-review

#2405 Release kafka 2.8.0-2.3.0 (automated commit)
  repo/packages/K/kafka/900/config.json
  repo/packages/K/kafka/900/marathon.json.mustache
  repo/packages/K/kafka/900/package.json
  repo/packages/K/kafka/900/resource.json
Labels: ready-for-review

#2411 Release kubernetes 2.4.4-1.15.4 (automated commit)
  repo/packages/K/kubernetes/2500/config.json
  repo/packages/K/kubernetes/2500/marathon.json.mustache
  repo/packages/K/kubernetes/2500/package.json
  repo/packages/K/kubernetes/2500/resource.json
Labels: ready-for-review

#2412 Release kubernetes-cluster 2.4.4-1.15.4 (automated commit)
  repo/packages/K/kubernetes-cluster/1500/config.json
  repo/packages/K/kubernetes-cluster/1500/marathon.json.mustache
  repo/packages/K/kubernetes-cluster/1500/package.json
  repo/packages/K/kubernetes-cluster/1500/resource.json
Labels: ready-for-review

#2409 Release elastic 3.0.0-7.3.2 (automated commit)
  repo/packages/E/elastic/800/config.json
  repo/packages/E/elastic/800/marathon.json.mustache
  repo/packages/E/elastic/800/package.json
  repo/packages/E/elastic/800/resource.json
Labels: ready-to-merge

#2410 Release kibana 3.0.0-7.3.2 (automated commit)
  repo/packages/K/kibana/800/config.json
  repo/packages/K/kibana/800/marathon.json.mustache
  repo/packages/K/kibana/800/package.json
  repo/packages/K/kibana/800/resource.json
Labels: ready-to-merge

#2408 Enables Connector classes in Confluent Replicator
  repo/packages/C/confluent-replicator/200/marathon.json.mustache
Labels: awaiting-testing-approval

#2417 [DCOS-60127] Make it possible to run replicator in multiple instances.
  repo/packages/C/confluent-replicator/200/marathon.json.mustache
Labels: ready-for-review

#2420 Make it possible to run connect in multiple instances
  repo/packages/C/confluent-connect/300/marathon.json.mustache
Labels: ready-for-review

#2419 Update cli test v3 helloworld branch
  .gitignore
  README.md
  converter/marathon.json
  converter/service/converter.py
  docker/local-universe/Dockerfile.base
  docker/local-universe/Makefile
  docker/local-universe/README.md
  docker/local-universe/default.conf
  docker/server/build.bash
  docker/server/nginx/etc/nginx/conf.d/universe.marathon.mesos.conf
  repo/meta/schema/README.md
  repo/meta/schema/build-definition-schema.json
  repo/meta/schema/metadata-schema.json
  repo/meta/schema/package-schema.json
  repo/meta/schema/vX-repo-definitions.json
  scripts/gen_universe.py
  scripts/local-universe.py
  scripts/requirements/requirements.txt
  scripts/validate_packages.py
Labels: ready-for-review

#2421 Update helloworld package with new CLI binaries
  repo/packages/H/helloworld/0/command.json
  repo/packages/H/helloworld/0/package.json
  repo/packages/H/helloworld/0/resource.json
Labels: ready-for-review

#2427 Release kubernetes 2.4.5-1.15.5 (automated commit)
  repo/packages/K/kubernetes/2600/config.json
  repo/packages/K/kubernetes/2600/marathon.json.mustache
  repo/packages/K/kubernetes/2600/package.json
  repo/packages/K/kubernetes/2600/resource.json
Labels: ready-for-review

#2428 Release kubernetes-cluster 2.4.5-1.15.5 (automated commit)
  repo/packages/K/kubernetes-cluster/1600/config.json
  repo/packages/K/kubernetes-cluster/1600/marathon.json.mustache
  repo/packages/K/kubernetes-cluster/1600/package.json
  repo/packages/K/kubernetes-cluster/1600/resource.json
Labels: ready-for-review

#2426 Add CODEOWNERS file
  CODEOWNERS
Labels: ready-for-review

#2430 Release jenkins 3.6.0-2.190.1 (automated commit)
  repo/packages/J/jenkins/40/config.json
  repo/packages/J/jenkins/40/marathon.json.mustache
  repo/packages/J/jenkins/40/package.json
  repo/packages/J/jenkins/40/resource.json
Labels: ready-for-review

#2431 Update CODEOWNERS for jenkins and other tooling
  CODEOWNERS
Labels: ready-for-review

#2433 Release dcos-monitoring v1.1.0 (automated commit)
  repo/packages/D/dcos-monitoring/10100/config.json
  repo/packages/D/dcos-monitoring/10100/marathon.json.mustache
  repo/packages/D/dcos-monitoring/10100/package.json
  repo/packages/D/dcos-monitoring/10100/resource.json
Labels: ready-for-review
