Repository mesosphere/universe, pull requests merged in 2019-06, with the labels that each got.

#2297 Fix broken URLs for (confluent-)kafka
  repo/packages/C/confluent-kafka/500/package.json
  repo/packages/C/confluent-kafka/600/package.json
  repo/packages/K/kafka/500/package.json
  repo/packages/K/kafka/600/package.json
Labels: ready-for-review

#2299 Release kubernetes 2.3.3-1.14.3 (automated commit)
  repo/packages/K/kubernetes/2000/config.json
  repo/packages/K/kubernetes/2000/marathon.json.mustache
  repo/packages/K/kubernetes/2000/package.json
  repo/packages/K/kubernetes/2000/resource.json
Labels: ready-for-review

#2300 Release kubernetes-cluster 2.3.3-1.14.3 (automated commit)
  repo/packages/K/kubernetes-cluster/1000/config.json
  repo/packages/K/kubernetes-cluster/1000/marathon.json.mustache
  repo/packages/K/kubernetes-cluster/1000/package.json
  repo/packages/K/kubernetes-cluster/1000/resource.json
Labels: ready-for-review

#2309 Marathon 1.6 bump to 687
  repo/packages/M/marathon/204/config.json
  repo/packages/M/marathon/204/marathon.json.mustache
  repo/packages/M/marathon/204/package.json
  repo/packages/M/marathon/204/resource.json
Labels: ready-for-review

#2316 Release dcos-monitoring v1.0.0 (automated commit)
  repo/packages/D/dcos-monitoring/10000/config.json
  repo/packages/D/dcos-monitoring/10000/marathon.json.mustache
  repo/packages/D/dcos-monitoring/10000/package.json
  repo/packages/D/dcos-monitoring/10000/resource.json
Labels: ready-for-review

#2289 Release spinnaker 0.3.1-1.9.2
  repo/packages/S/spinnaker/3/config.json
  repo/packages/S/spinnaker/3/marathon.json.mustache
  repo/packages/S/spinnaker/3/package.json
  repo/packages/S/spinnaker/3/resource.json
Labels: ready-for-review

#2318 [DCOS-51992] Auditing and changing Non-HTTPS resources & references to HTTPS
  repo/packages/C/confluent-kafka/500/resource.json
  repo/packages/C/confluent-kafka/600/resource.json
  repo/packages/D/datastax-dse/400/config.json
  repo/packages/D/datastax-dse/500/config.json
  repo/packages/D/datastax-ops/400/config.json
  repo/packages/D/datastax-ops/500/config.json
  repo/packages/H/hdfs/400/resource.json
  repo/packages/K/kafka-zookeeper/300/resource.json
  repo/packages/K/kafka/500/resource.json
  repo/packages/K/kafka/600/resource.json
Labels: ready-for-review

#2319 Release portworx-confluent-kafka 1.3-2.6.0-5.1.2 (automated commit)
  repo/packages/P/portworx-confluent-kafka/100/config.json
  repo/packages/P/portworx-confluent-kafka/100/marathon.json.mustache
  repo/packages/P/portworx-confluent-kafka/100/package.json
  repo/packages/P/portworx-confluent-kafka/100/resource.json
Labels: awaiting-testing-approval

#2313 Release confluent-control-center 2.6.0-5.1.2 (automated commit)
  repo/packages/C/confluent-control-center/100/config.json
  repo/packages/C/confluent-control-center/100/marathon.json.mustache
  repo/packages/C/confluent-control-center/100/package.json
  repo/packages/C/confluent-control-center/100/resource.json
Labels: ready-for-review

#2312 Release confluent-replicator 2.6.0-5.1.2 (automated commit)
  repo/packages/C/confluent-replicator/100/config.json
  repo/packages/C/confluent-replicator/100/marathon.json.mustache
  repo/packages/C/confluent-replicator/100/package.json
  repo/packages/C/confluent-replicator/100/resource.json
Labels: ready-for-review

#2311 Release confluent-rest-proxy 2.6.0-5.1.2 (automated commit)
  repo/packages/C/confluent-rest-proxy/100/config.json
  repo/packages/C/confluent-rest-proxy/100/marathon.json.mustache
  repo/packages/C/confluent-rest-proxy/100/package.json
  repo/packages/C/confluent-rest-proxy/100/resource.json
Labels: ready-for-review

#2310 Release confluent-connect 2.6.0-5.1.2 (automated commit)
  repo/packages/C/confluent-connect/100/config.json
  repo/packages/C/confluent-connect/100/marathon.json.mustache
  repo/packages/C/confluent-connect/100/package.json
  repo/packages/C/confluent-connect/100/resource.json
Labels: ready-for-review

#2302 Release kafka 2.6.0-2.2.1 (automated commit)
  repo/packages/K/kafka/700/config.json
  repo/packages/K/kafka/700/marathon.json.mustache
  repo/packages/K/kafka/700/package.json
  repo/packages/K/kafka/700/resource.json
Labels: ready-for-review

#2303 Release kafka-zookeeper 2.6.0-3.4.14 (automated commit)
  repo/packages/K/kafka-zookeeper/500/config.json
  repo/packages/K/kafka-zookeeper/500/marathon.json.mustache
  repo/packages/K/kafka-zookeeper/500/package.json
  repo/packages/K/kafka-zookeeper/500/resource.json
Labels: ready-for-review

#2314 Release confluent-schema-registry 2.6.0-5.1.2 (automated commit)
  repo/packages/C/confluent-schema-registry/100/config.json
  repo/packages/C/confluent-schema-registry/100/marathon.json.mustache
  repo/packages/C/confluent-schema-registry/100/package.json
  repo/packages/C/confluent-schema-registry/100/resource.json
Labels: ready-for-review

#2288 Release nifi 0.5.0-1.9.2 (automated commit)
  repo/packages/N/nifi/600/config.json
  repo/packages/N/nifi/600/marathon.json.mustache
  repo/packages/N/nifi/600/package.json
  repo/packages/N/nifi/600/resource.json
Labels: ready-for-review

#2321 [DCOS-54580] Updated universe packages catalogue icons for DSE and OPS package
  repo/packages/D/datastax-dse/400/resource.json
  repo/packages/D/datastax-dse/500/resource.json
  repo/packages/D/datastax-ops/400/resource.json
  repo/packages/D/datastax-ops/500/resource.json
Labels: ready-for-review

#2293 Couchbase release 1.0.0-6.0.0
  repo/packages/C/couchbase/3/config.json
  repo/packages/C/couchbase/3/marathon.json.mustache
  repo/packages/C/couchbase/3/package.json
  repo/packages/C/couchbase/3/resource.json
Labels: do-not-merge, ready-for-review

#2296 Release beta-portworx-jupyter-service 1.3.0-0.35.4-beta (automated co…
  repo/packages/B/beta-portworx-jupyter-service/0/config.json
  repo/packages/B/beta-portworx-jupyter-service/0/marathon.json.mustache
  repo/packages/B/beta-portworx-jupyter-service/0/package.json
  repo/packages/B/beta-portworx-jupyter-service/0/resource.json
Labels: awaiting-testing-approval

#2323 Add dcos-core-cli patch.5
  repo/packages/D/dcos-core-cli/1305/package.json
  repo/packages/D/dcos-core-cli/1305/resource.json
Labels: ready-for-review
