Repository mesosphere/universe, pull requests merged in 2019-08, with the labels that each got.

#2341 add configuration option in schema registry to bootstrap servers
  repo/packages/C/confluent-schema-registry/100/config.json
  repo/packages/C/confluent-schema-registry/100/marathon.json.mustache
Labels: ready-for-review

#2343 Release kubernetes 2.4.0-1.15.1 (automated commit)
  repo/packages/K/kubernetes/2100/config.json
  repo/packages/K/kubernetes/2100/marathon.json.mustache
  repo/packages/K/kubernetes/2100/package.json
  repo/packages/K/kubernetes/2100/resource.json
Labels: ready-for-review

#2342 Release kubernetes-cluster 2.4.0-1.15.1 (automated commit)
  repo/packages/K/kubernetes-cluster/1100/config.json
  repo/packages/K/kubernetes-cluster/1100/marathon.json.mustache
  repo/packages/K/kubernetes-cluster/1100/package.json
  repo/packages/K/kubernetes-cluster/1100/resource.json
Labels: ready-for-review

#2344 fix the parsing error in confluent schema registry
  repo/packages/C/confluent-schema-registry/100/marathon.json.mustache
Labels: ready-for-review

#2347 [DCOS-57182] Release Data Science Engine 1.0.0 GA
  repo/packages/D/data-science-engine/0/config.json
  repo/packages/D/data-science-engine/0/marathon.json.mustache
  repo/packages/D/data-science-engine/0/package.json
  repo/packages/D/data-science-engine/0/resource.json
Labels: ready-for-review

#2346 Release dcos-monitoring v1.0.2 (automated commit)
  repo/packages/D/dcos-monitoring/10002/config.json
  repo/packages/D/dcos-monitoring/10002/marathon.json.mustache
  repo/packages/D/dcos-monitoring/10002/package.json
  repo/packages/D/dcos-monitoring/10002/resource.json
Labels: ready-for-review

#2349 Add dcos-core-cli 1.14-patch.3
  repo/packages/D/dcos-core-cli/1403/package.json
  repo/packages/D/dcos-core-cli/1403/resource.json
Labels: ready-for-review

#2339 Release HiveMQ 4.2.0
  repo/packages/H/hivemq/1/config.json
  repo/packages/H/hivemq/1/marathon.json.mustache
  repo/packages/H/hivemq/1/package.json
  repo/packages/H/hivemq/1/resource.json
Labels: awaiting-testing-approval

#2353 Release kafka 2.7.0-2.3.0 (automated commit)
  repo/packages/K/kafka/800/config.json
  repo/packages/K/kafka/800/marathon.json.mustache
  repo/packages/K/kafka/800/package.json
  repo/packages/K/kafka/800/resource.json
Labels: ready-for-review, ready-to-merge

#2350 Release hdfs 2.6.0-3.2.0 (automated commit)
  repo/packages/H/hdfs/600/config.json
  repo/packages/H/hdfs/600/marathon.json.mustache
  repo/packages/H/hdfs/600/package.json
  repo/packages/H/hdfs/600/resource.json
Labels: ready-for-review

#2356 Release elastic 2.7.0-6.8.1 (automated commit)
  repo/packages/E/elastic/700/config.json
  repo/packages/E/elastic/700/marathon.json.mustache
  repo/packages/E/elastic/700/package.json
  repo/packages/E/elastic/700/resource.json
Labels: ready-for-review

#2357 Release kibana 2.7.0-6.8.1 (automated commit)
  repo/packages/K/kibana/700/config.json
  repo/packages/K/kibana/700/marathon.json.mustache
  repo/packages/K/kibana/700/package.json
  repo/packages/K/kibana/700/resource.json
Labels: ready-for-review

#2355 Release kubernetes 2.4.1-1.15.2 (automated commit)
  repo/packages/K/kubernetes/2200/config.json
  repo/packages/K/kubernetes/2200/marathon.json.mustache
  repo/packages/K/kubernetes/2200/package.json
  repo/packages/K/kubernetes/2200/resource.json
Labels: ready-for-review

#2354 Release kubernetes-cluster 2.4.1-1.15.2 (automated commit)
  repo/packages/K/kubernetes-cluster/1200/config.json
  repo/packages/K/kubernetes-cluster/1200/marathon.json.mustache
  repo/packages/K/kubernetes-cluster/1200/package.json
  repo/packages/K/kubernetes-cluster/1200/resource.json
Labels: ready-for-review

#2331 [DOCS] Add notes on creating CA certificate in local universe
  docker/local-universe/Makefile
  docker/local-universe/README.md
Labels: ready-for-review

#2358 Release dcos-core-cli 1.14-patch.4
  repo/packages/D/dcos-core-cli/1404/package.json
  repo/packages/D/dcos-core-cli/1404/resource.json
Labels: ready-for-review

#2361 Fix Kibana 2.6.0-6.8.1 asset paths.
  repo/packages/K/kibana/700/marathon.json.mustache
Labels: ready-for-review
