Repository mesosphere/universe, pull requests merged in 2019-01, with the labels that each got.

#2086 Fix mongodb licenses
  repo/packages/P/percona-mongo/0/package.json
  repo/packages/P/percona-mongo/1/package.json
  repo/packages/P/percona-mongo/100/package.json
  repo/packages/P/percona-mongo/200/package.json
  repo/packages/P/percona-server-mongodb/0/package.json
  repo/packages/P/portworx-percona-mongo/0/package.json
Labels: requested-changes

#2085 Fix kubernetes license
  repo/packages/K/kubernetes-cluster/0/package.json
  repo/packages/K/kubernetes-cluster/100/package.json
  repo/packages/K/kubernetes-cluster/200/package.json
  repo/packages/K/kubernetes/0/package.json
  repo/packages/K/kubernetes/100/package.json
  repo/packages/K/kubernetes/1000/package.json
  repo/packages/K/kubernetes/1100/package.json
  repo/packages/K/kubernetes/1200/package.json
  repo/packages/K/kubernetes/200/package.json
  repo/packages/K/kubernetes/300/package.json
  repo/packages/K/kubernetes/400/package.json
  repo/packages/K/kubernetes/500/package.json
  repo/packages/K/kubernetes/600/package.json
  repo/packages/K/kubernetes/700/package.json
  repo/packages/K/kubernetes/800/package.json
  repo/packages/K/kubernetes/900/package.json
Labels: ready-for-review

#2070 Add nifi license field
  repo/packages/N/nifi/100/package.json
  repo/packages/N/nifi/200/package.json
Labels: ready-for-review

#2084 Fix zookeeper licenses
  repo/packages/B/beta-kafka-zookeeper/0/package.json
  repo/packages/B/beta-kafka-zookeeper/1/package.json
  repo/packages/B/beta-kafka-zookeeper/2/package.json
  repo/packages/K/kafka-zookeeper/0/package.json
  repo/packages/K/kafka-zookeeper/100/package.json
  repo/packages/K/kafka-zookeeper/200/package.json
  repo/packages/K/kafka-zookeeper/300/package.json
  repo/packages/P/portworx-zookeeper/0/package.json
  repo/packages/P/portworx-zookeeper/1/package.json
  repo/packages/P/portworx-zookeeper/100/package.json
Labels: ready-for-review

#2081 Fix couchbase licenses
  repo/packages/C/couchbase/0/package.json
  repo/packages/C/couchbase/1/package.json
Labels: ready-for-review

#2075 Fix scylladb license
  repo/packages/S/scylladb/0/package.json
Labels: ready-for-review

#2069 Update license for instana
  repo/packages/I/instana-agent/0/package.json
  repo/packages/I/instana-agent/1/package.json
  repo/packages/I/instana-agent/2/package.json
Labels: ready-for-review

#2071 Fix zeppelin licenses
  repo/packages/Z/zeppelin/0/package.json
  repo/packages/Z/zeppelin/1/package.json
  repo/packages/Z/zeppelin/2/package.json
  repo/packages/Z/zeppelin/3/package.json
  repo/packages/Z/zeppelin/4/package.json
  repo/packages/Z/zeppelin/5/package.json
  repo/packages/Z/zeppelin/6/package.json
  repo/packages/Z/zeppelin/7/package.json
  repo/packages/Z/zeppelin/8/package.json
Labels: ready-for-review

#2082 Fix dcos-core-cli licenses
  repo/packages/D/dcos-core-cli/1200/package.json
  repo/packages/D/dcos-core-cli/1201/package.json
  repo/packages/D/dcos-core-cli/1202/package.json
Labels: ready-for-review

#2079 Fix cassandra licenses
  repo/packages/B/beta-cassandra/0/package.json
  repo/packages/B/beta-cassandra/1/package.json
  repo/packages/B/beta-cassandra/2/package.json
  repo/packages/B/beta-cassandra/3/package.json
  repo/packages/B/beta-cassandra/4/package.json
  repo/packages/B/beta-cassandra/5/package.json
  repo/packages/B/beta-cassandra/6/package.json
  repo/packages/B/beta-cassandra/7/package.json
  repo/packages/B/beta-cassandra/8/package.json
  repo/packages/C/cassandra/10/package.json
  repo/packages/C/cassandra/100/package.json
  repo/packages/C/cassandra/11/package.json
  repo/packages/C/cassandra/12/package.json
  repo/packages/C/cassandra/13/package.json
  repo/packages/C/cassandra/14/package.json
  repo/packages/C/cassandra/15/package.json
  repo/packages/C/cassandra/16/package.json
  repo/packages/C/cassandra/17/package.json
  repo/packages/C/cassandra/18/package.json
  repo/packages/C/cassandra/20/package.json
  repo/packages/C/cassandra/200/package.json
  repo/packages/C/cassandra/21/package.json
  repo/packages/C/cassandra/22/package.json
  repo/packages/C/cassandra/23/package.json
  repo/packages/C/cassandra/24/package.json
  repo/packages/C/cassandra/25/package.json
  repo/packages/C/cassandra/26/package.json
  repo/packages/C/cassandra/27/package.json
  repo/packages/C/cassandra/28/package.json
  repo/packages/C/cassandra/29/package.json
  repo/packages/C/cassandra/300/package.json
  repo/packages/C/cassandra/4/package.json
  repo/packages/C/cassandra/400/package.json
  repo/packages/C/cassandra/5/package.json
  repo/packages/C/cassandra/6/package.json
  repo/packages/C/cassandra/7/package.json
  repo/packages/C/cassandra/8/package.json
  repo/packages/C/cassandra/9/package.json
  repo/packages/P/portworx-cassandra/0/package.json
  repo/packages/P/portworx-cassandra/1/package.json
  repo/packages/P/portworx-cassandra/100/package.json
  repo/packages/P/portworx-cassandra/200/package.json
Labels: ready-for-review

#2077 Fix HDFS licenses
  repo/packages/B/beta-hdfs/0/package.json
  repo/packages/B/beta-hdfs/1/package.json
  repo/packages/B/beta-hdfs/2/package.json
  repo/packages/B/beta-hdfs/3/package.json
  repo/packages/B/beta-hdfs/4/package.json
  repo/packages/B/beta-hdfs/5/package.json
  repo/packages/B/beta-hdfs/6/package.json
  repo/packages/B/beta-hdfs/7/package.json
  repo/packages/H/hdfs/10/package.json
  repo/packages/H/hdfs/100/package.json
  repo/packages/H/hdfs/11/package.json
  repo/packages/H/hdfs/12/package.json
  repo/packages/H/hdfs/13/package.json
  repo/packages/H/hdfs/14/package.json
  repo/packages/H/hdfs/15/package.json
  repo/packages/H/hdfs/16/package.json
  repo/packages/H/hdfs/2/package.json
  repo/packages/H/hdfs/200/package.json
  repo/packages/H/hdfs/3/package.json
  repo/packages/H/hdfs/300/package.json
  repo/packages/H/hdfs/4/package.json
  repo/packages/H/hdfs/400/package.json
  repo/packages/H/hdfs/5/package.json
  repo/packages/H/hdfs/6/package.json
  repo/packages/H/hdfs/7/package.json
  repo/packages/H/hdfs/8/package.json
  repo/packages/H/hdfs/9/package.json
Labels: ready-for-review

#2076 Add licenses for hello-world
  repo/packages/H/hello-world/0/package.json
  repo/packages/H/hello-world/1/package.json
  repo/packages/H/hello-world/10/package.json
  repo/packages/H/hello-world/100/package.json
  repo/packages/H/hello-world/11/package.json
  repo/packages/H/hello-world/12/package.json
  repo/packages/H/hello-world/13/package.json
  repo/packages/H/hello-world/14/package.json
  repo/packages/H/hello-world/15/package.json
  repo/packages/H/hello-world/16/package.json
  repo/packages/H/hello-world/2/package.json
  repo/packages/H/hello-world/200/package.json
  repo/packages/H/hello-world/3/package.json
  repo/packages/H/hello-world/300/package.json
  repo/packages/H/hello-world/4/package.json
  repo/packages/H/hello-world/5/package.json
  repo/packages/H/hello-world/6/package.json
  repo/packages/H/hello-world/7/package.json
  repo/packages/H/hello-world/8/package.json
  repo/packages/H/hello-world/9/package.json
Labels: ready-for-review

#2058 Fix datastax licenses
  repo/packages/B/beta-datastax-dse/0/package.json
  repo/packages/B/beta-datastax-dse/1/package.json
  repo/packages/B/beta-datastax-dse/2/package.json
  repo/packages/B/beta-datastax-ops/0/package.json
  repo/packages/B/beta-datastax-ops/1/package.json
  repo/packages/B/beta-datastax-ops/2/package.json
  repo/packages/B/beta-dse-opscenter/0/package.json
  repo/packages/B/beta-dse/0/package.json
  repo/packages/B/beta-dse/1/package.json
  repo/packages/B/beta-dse/2/package.json
  repo/packages/B/beta-dse/3/package.json
  repo/packages/B/beta-dse/4/package.json
  repo/packages/D/datastax-dse/0/package.json
  repo/packages/D/datastax-dse/1/package.json
  repo/packages/D/datastax-dse/100/package.json
  repo/packages/D/datastax-dse/2/package.json
  repo/packages/D/datastax-dse/200/package.json
  repo/packages/D/datastax-dse/3/package.json
  repo/packages/D/datastax-dse/300/package.json
  repo/packages/D/datastax-dse/4/package.json
  repo/packages/D/datastax-dse/400/package.json
  repo/packages/D/datastax-dse/5/package.json
  repo/packages/D/datastax-ops/0/package.json
  repo/packages/D/datastax-ops/1/package.json
  repo/packages/D/datastax-ops/100/package.json
  repo/packages/D/datastax-ops/2/package.json
  repo/packages/D/datastax-ops/200/package.json
  repo/packages/D/datastax-ops/3/package.json
  repo/packages/D/datastax-ops/300/package.json
  repo/packages/D/datastax-ops/4/package.json
  repo/packages/D/datastax-ops/400/package.json
  repo/packages/P/portworx-datastax-dse/0/package.json
  repo/packages/P/portworx-datastax-dse/100/package.json
  repo/packages/P/portworx-datastax-ops/0/package.json
  repo/packages/P/portworx-datastax-ops/100/package.json
Labels: ready-for-review

#2068 Fix licenses and tags for elastic stack
  repo/packages/B/beta-elastic/0/package.json
  repo/packages/B/beta-elastic/1/package.json
  repo/packages/B/beta-elastic/10/package.json
  repo/packages/B/beta-elastic/2/package.json
  repo/packages/B/beta-elastic/3/package.json
  repo/packages/B/beta-elastic/4/package.json
  repo/packages/B/beta-elastic/5/package.json
  repo/packages/B/beta-elastic/6/package.json
  repo/packages/B/beta-elastic/7/package.json
  repo/packages/B/beta-elastic/8/package.json
  repo/packages/B/beta-elastic/9/package.json
  repo/packages/B/beta-kibana/0/package.json
  repo/packages/B/beta-kibana/1/package.json
  repo/packages/B/beta-kibana/2/package.json
  repo/packages/B/beta-kibana/3/package.json
  repo/packages/B/beta-kibana/4/package.json
  repo/packages/B/beta-kibana/5/package.json
  repo/packages/B/beta-kibana/6/package.json
  repo/packages/B/beta-kibana/7/package.json
  repo/packages/E/elastic/0/package.json
  repo/packages/E/elastic/1/package.json
  repo/packages/E/elastic/100/package.json
  repo/packages/E/elastic/2/package.json
  repo/packages/E/elastic/200/package.json
  repo/packages/E/elastic/3/package.json
  repo/packages/E/elastic/300/package.json
  repo/packages/E/elastic/4/package.json
  repo/packages/E/elastic/400/package.json
  repo/packages/E/elastic/5/package.json
  repo/packages/E/elastic/6/package.json
  repo/packages/E/elastic/7/package.json
  repo/packages/E/elastic/8/package.json
  repo/packages/E/elastic/9/package.json
  repo/packages/K/kibana/0/package.json
  repo/packages/K/kibana/1/package.json
  repo/packages/K/kibana/100/package.json
  repo/packages/K/kibana/2/package.json
  repo/packages/K/kibana/200/package.json
  repo/packages/K/kibana/3/package.json
  repo/packages/K/kibana/300/package.json
  repo/packages/K/kibana/4/package.json
  repo/packages/K/kibana/400/package.json
  repo/packages/K/kibana/5/package.json
  repo/packages/L/logstash/0/package.json
Labels: ready-for-review

#2073 Fix spinnaker licenses
  repo/packages/S/spinnaker/0/package.json
  repo/packages/S/spinnaker/1/package.json
  repo/packages/S/spinnaker/2/package.json
Labels: ready-for-review

#2017 Support GPU scheduling behavior (MARATHON-8088,MARATHON-8089)
  repo/packages/M/marathon/203/config.json
  repo/packages/M/marathon/203/marathon.json.mustache
  repo/packages/M/marathon/203/package.json
  repo/packages/M/marathon/203/resource.json
Labels: awaiting-testing-approval

#2010 Update to Traefik 1.7.3
  repo/packages/T/traefik/4/config.json
  repo/packages/T/traefik/4/marathon.json.mustache
  repo/packages/T/traefik/4/package.json
  repo/packages/T/traefik/4/resource.json
Labels: awaiting-testing-approval

#2117 cloudflare argotunnel rel 0.1.0
  repo/packages/C/cloudflare-argotunnel/0/config.json
  repo/packages/C/cloudflare-argotunnel/0/marathon.json.mustache
  repo/packages/C/cloudflare-argotunnel/0/package.json
  repo/packages/C/cloudflare-argotunnel/0/resource.json
Labels: ready-for-review

#2061 adding Marathon 1.7.174 to the universe
  repo/packages/M/marathon/300/config.json
  repo/packages/M/marathon/300/marathon.json.mustache
  repo/packages/M/marathon/300/package.json
  repo/packages/M/marathon/300/resource.json
Labels: ready-for-review

#2121 Kong 0.15.0 and 1.0.0 support
  repo/packages/K/kong/13/config.json
  repo/packages/K/kong/13/marathon.json.mustache
  repo/packages/K/kong/13/package.json
  repo/packages/K/kong/13/resource.json
  repo/packages/K/kong/14/config.json
  repo/packages/K/kong/14/marathon.json.mustache
  repo/packages/K/kong/14/package.json
  repo/packages/K/kong/14/resource.json
Labels: awaiting-testing-approval

#2057 Fix README to add license section
  README.md
Labels: ready-for-review

#2122 Released dcos-core-cli 1.12-patch.5
  repo/packages/D/dcos-core-cli/1205/package.json
  repo/packages/D/dcos-core-cli/1205/resource.json
Labels: ready-for-review

#2126 Add checks to validate mustache templating in Universe CI
  scripts/requirements/requirements.txt
  scripts/validate_packages.py
Labels: ready-for-review

#2127 Release portworx 1.3.4-2.0.1 (automated commit)
  repo/packages/P/portworx/1100/config.json
  repo/packages/P/portworx/1100/marathon.json.mustache
  repo/packages/P/portworx/1100/package.json
  repo/packages/P/portworx/1100/resource.json
Labels: awaiting-testing-approval

#2128 Release dcos-enterprise-cli 1.12-patch.0
  repo/packages/D/dcos-enterprise-cli/1200/package.json
  repo/packages/D/dcos-enterprise-cli/1200/resource.json
Labels: ready-for-review

#2141 Kong 1.0.2 support
  repo/packages/K/kong/15/config.json
  repo/packages/K/kong/15/marathon.json.mustache
  repo/packages/K/kong/15/package.json
  repo/packages/K/kong/15/resource.json
Labels: awaiting-testing-approval

#2123 Release hdfs 2.5.0-2.6.0-cdh5.11.0 (automated commit)
  repo/packages/H/hdfs/500/config.json
  repo/packages/H/hdfs/500/marathon.json.mustache
  repo/packages/H/hdfs/500/package.json
  repo/packages/H/hdfs/500/resource.json
Labels: ready-for-review

#2152 Release beta-cassandra 2.5.0-3.0.16-beta (automated commit)
  repo/packages/B/beta-cassandra/100/config.json
  repo/packages/B/beta-cassandra/100/marathon.json.mustache
  repo/packages/B/beta-cassandra/100/package.json
  repo/packages/B/beta-cassandra/100/resource.json
Labels: ready-for-review

#2154 Release beta-elastic 2.6.0-6.3.2-beta (automated commit)
  repo/packages/B/beta-elastic/100/config.json
  repo/packages/B/beta-elastic/100/marathon.json.mustache
  repo/packages/B/beta-elastic/100/package.json
  repo/packages/B/beta-elastic/100/resource.json
Labels: ready-for-review

#2153 Release beta-hdfs 2.6.0-2.6.0-cdh5.11.0-beta (automated commit)
  repo/packages/B/beta-hdfs/100/config.json
  repo/packages/B/beta-hdfs/100/marathon.json.mustache
  repo/packages/B/beta-hdfs/100/package.json
  repo/packages/B/beta-hdfs/100/resource.json
Labels: ready-for-review

#2055 miniod release
  repo/packages/M/miniod/0/config.json
  repo/packages/M/miniod/0/marathon.json.mustache
  repo/packages/M/miniod/0/package.json
  repo/packages/M/miniod/0/resource.json
Labels: ready-for-review

#2162 Release beta-dcos-monitoring v0.4.0-beta (automated commit)
  repo/packages/B/beta-dcos-monitoring/400/config.json
  repo/packages/B/beta-dcos-monitoring/400/marathon.json.mustache
  repo/packages/B/beta-dcos-monitoring/400/package.json
  repo/packages/B/beta-dcos-monitoring/400/resource.json
Labels: ready-for-review

#2167 Release beta-dcos-monitoring v0.4.2-beta (automated commit)
  repo/packages/B/beta-dcos-monitoring/402/config.json
  repo/packages/B/beta-dcos-monitoring/402/marathon.json.mustache
  repo/packages/B/beta-dcos-monitoring/402/package.json
  repo/packages/B/beta-dcos-monitoring/402/resource.json
Labels: ready-for-review
